### ISSUE TITLE
Bridgehead processing is broken

### ISSUE THREAD

**Issue by tradej** [asciidoctor/docbookrx#44]
When converting a document containing a `<bridgehead>` tag, I get the following traceback:
```
/home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:459:in `visit_bridgehead': undefined method `sub' for nil:NilClass (NoMethodError)
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:133:in `visit'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:595:in `accept'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:144:in `block in traverse_children'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:143:in `traverse_children'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:515:in `process_section'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:133:in `visit'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:595:in `accept'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:144:in `block in traverse_children'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:143:in `traverse_children'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:515:in `process_section'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:366:in `visit_chapter'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx/docbook_visitor.rb:133:in `visit'
	from /home/tradej/.gem/ruby/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb:595:in `accept'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx.rb:12:in `convert'
	from /home/tradej/red-hat/git/docbookrx/lib/docbookrx.rb:24:in `convert_file'
	from /home/tradej/red-hat/git/docbookrx/bin/docbookrx:32:in `<main>'
```

**Comment by mrietveld** [comment]
Fixed here: https://github.com/mrietveld/docbookrx/commit/b1483c324a246aa7899eba3775b9c27f43c1ee6c

**Comment by mrietveld** [comment]
@tradej Could you verify for me that bridgehead processing is now fixed?

**Comment by tradej** [comment]
Yep, seems to work fine.
